### ISSUE TITLE
Repository should do context swithing

### ISSUE THREAD

**Issue by dmytrodanylyk** [AidanLaing/Exoplanets#10]
Currently, your `PlanetsRepo` provides `suspend` functions, without context switching, which means caller (ViewModel) must do that.

I think it's better to move this responsibility to `PlanetsRepo`. E.g.

```kotlin
// PlanetsRepo.kt

override suspend fun getPlanets(): Result<ArrayList<Planet>> {
        ...

        val localResult = withContext(dbDispatcher) { localDataSource.getPlanets() }
        ...

        val remoteResult = withContext(networkDispatcher) { remoteDataSource.getPlanets() }
        ...
    }
```

**Comment by AidanLaing** [comment]
Thanks @dmytrodanylyk for the feedback! Will make the change.
