### ISSUE TITLE
Can you please add the scope to the repo introduced recently 

### ISSUE THREAD

**Issue by nksaroj** [AidanLaing/Exoplanets#11]
Thanks for making such a nice example and I follow your template 
Can you apply the scope to the example?
https://medium.com/@elizarov/structured-concurrency-722d765aa952

**Comment by AidanLaing** [comment]
Hi nksaroj.

You can add a BaseViewModel that extends CoroutineScope and apply it to all your ViewModels:
`abstract class BaseViewModel : ViewModel(), CoroutineScope {
    private val job = Job()
    override val coroutineContext: CoroutineContext
        get() = Dispatchers.Main + job

    override fun onCleared() {
        super.onCleared()
        job.cancel()
    }
}`

**Comment by nksaroj** [comment]
Thanks @AidanLaing!

I've got a question here for you but not sure how to solve the issue. Your suggestion is appreciated.

```
    override suspend fun getPlanets(): Result<ArrayList<Planet>> {
        val cached = cachedPlanets.values
        if (cached.isNotEmpty()) {
            return Result.Success(ArrayList(cached))
        }

        val localResult = withContext(dispatchers.database) { localDataSource.getPlanets() }
        if (localResult is Result.Success) {
            val data = localResult.data
            if (data.isNotEmpty()) {
                cachePlanets(data)
                return localResult
            }
        }

        val remoteResult = withContext(dispatchers.network) { remoteDataSource.getPlanets() }
        return when (remoteResult) {
            is Result.Success -> {
                val data = remoteResult.data
                cachePlanets(data)
                savePlanets(data)
                remoteResult
            }
            is Result.Failure -> remoteResult
        }
    }

```
To narrate the problem let me the above code snippet from your sample and below are the step it happens:

1. VM makes call to this repo to display the plannets in the UI
2. Check the cache if exists and returns the data 
3. If no data in the ache check in the DB and return the data
4. If no data in cache then make a remote call.

With the above steps the user never see the updated plannet if there is a new plannet being added/updated in the remote server in the scenerio where if exists in the cache or in the DB.

I would like to show the cahce/db stale data when user landed on the page and seemlessly would like to udpate the refreshed content from the server also in the same time update the cache/db to display in the future.

Hope my question is quite clear. Thanks

**Comment by nksaroj** [comment]
I think we need to use live data all the way to the repository. It's antipattern to use live data in data layer but can't think of any better way or can be done another layer may be interactor. But not sure how the Coroutine will fit to live data between DAO and network that would return the LiveData<Result> may be.

**Comment by AidanLaing** [comment]
I would have two calls in the ViewModel. One for getting cached data / local data if it exists and one that gets from remote. You would populate the list instantly if the local data exists and then add any remaining new planets when the remote call returns using a ListAdapter.
