### ISSUE TITLE
Synchronize access to mutable fields

### ISSUE THREAD

**Issue by dmytrodanylyk** [AidanLaing/Exoplanets#8]
File: https://github.com/AidanLaing/Exoplanets/blob/master/app/src/main/java/com/aidanlaing/exoplanets/data/planets/PlanetsRepo.kt#L29

Issue:
Access to `cachedPlanets` is not synchronized, e.g. calling `cachePlanets` from 2 threads produces an unpredictable result.

Solution:
Synchronize access to `cachedPlanets` (synchronized, lock, coroutines Mutex) or use thread safe map.

**Comment by AidanLaing** [comment]
Thanks
