### ISSUE TITLE
CoroutineContext Issues

### ISSUE THREAD

**Issue by dmytrodanylyk** [AidanLaing/Exoplanets#9]
1. `CommonPool` is default thread coroutines pool which everyone uses by default. I suggest creating your own pool if you don't want to end up in a situation when your code is in "waiting state" because some libraries "doing stuff". 

2. Also, I suggest creating several different pool objects for different needs. E.g. disk, database, network, io.

**Comment by AidanLaing** [comment]
Would you use newFixedThreadPoolContext, newSingleThreadContext, or something else for creating pool objects?

**Comment by dmytrodanylyk** [comment]
It's really up to you to decide on thread count, see https://medium.com/@chrisbanes/rxjava-to-kotlin-coroutines-1204c896a700 as an example.

**Comment by AidanLaing** [comment]
Great I think I have it all setup. Thanks again.
